#!/usr/bin/env python3
"""
Generate the Paspor Arab Saudi seed migration from the reworked course content.

Pipeline:  paspor-arab-siap-kerja.json (program) + _rework/module-{1..6}.json
           → merged course JSON (overwrites the source, original backed up)
           → packages/db/migrations/0082_academy_seed_paspor_arab.sql

IDs are deterministic uuid5 (stable across re-runs), and the migration upserts
(ON CONFLICT DO UPDATE) so re-applying never duplicates and preserves enrollments.
Reading "chunk"/"media"/"anchor" + module "content" + per-option "rationale" are
all carried through as JSONB — no schema beyond migrations 0060/0085.
"""
import json, uuid, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs" / "akademi-perantau"
REWORK = DOCS / "_rework"
SRC = DOCS / "paspor-arab-siap-kerja.json"
OUT_SQL = ROOT / "packages" / "db" / "migrations" / "0082_academy_seed_paspor_arab.sql"

NS = uuid.UUID("6f9b2c1a-0d3e-5f47-a8b1-2c3d4e5f6071")  # fixed namespace for stable IDs
VALID_BLOCKS = {"heading", "paragraph", "list", "callout", "steps", "stat", "quote"}

errors, warnings = [], []


def die():
    print("\n".join("  ✗ " + e for e in errors))
    sys.exit(1)


def mid(slug, n):
    return str(uuid.uuid5(NS, f"{slug}:m{n}"))


def lid(slug, mnum, lnum):
    return str(uuid.uuid5(NS, f"{slug}:m{mnum}:l{lnum}"))


def dq(obj):
    """Dollar-quoted JSONB literal."""
    s = json.dumps(obj, ensure_ascii=False)
    if "$pg$" in s:
        errors.append("content contains the dollar-quote delimiter $pg$")
    return f"$pg${s}$pg$::jsonb"


def sql_str(s):
    if s is None:
        return "NULL"
    return "'" + str(s).replace("'", "''") + "'"


# ── load ────────────────────────────────────────────────────────────────────
course = json.loads(SRC.read_text())
program = course["program"]
slug = program["slug"]

modules = []
for n in range(1, 7):
    f = REWORK / f"module-{n}.json"
    if not f.exists():
        errors.append(f"missing {f}")
        continue
    try:
        m = json.loads(f.read_text())
    except Exception as e:
        errors.append(f"module-{n}.json invalid JSON: {e}")
        continue
    modules.append(m)

if errors:
    die()

# ── validate vs original lesson counts ────────────────────────────────────────
orig_by_num = {m["module_num"]: m for m in course["modules"]}
for m in modules:
    mn = m.get("module_num")
    if mn not in orig_by_num:
        errors.append(f"module_num {mn} not in original")
        continue
    o = orig_by_num[mn]
    if len(m.get("lessons", [])) != len(o["lessons"]):
        errors.append(
            f"M{mn}: lesson count {len(m.get('lessons', []))} != original {len(o['lessons'])}"
        )
    for l in m.get("lessons", []):
        lt = l.get("lesson_type")
        if lt == "reading":
            blocks = l.get("blocks") or []
            if not blocks:
                errors.append(f"M{mn} L{l.get('lesson_num')}: no blocks")
            for b in blocks:
                if b.get("type") not in VALID_BLOCKS:
                    errors.append(f"M{mn} L{l.get('lesson_num')}: bad block type {b.get('type')}")
        elif lt == "quiz":
            if not l.get("questions"):
                errors.append(f"M{mn} L{l.get('lesson_num')}: quiz has no questions")
            if not l.get("answerKeys"):
                errors.append(f"M{mn} L{l.get('lesson_num')}: quiz has no answerKeys")
        else:
            errors.append(f"M{mn} L{l.get('lesson_num')}: unknown lesson_type {lt}")

if errors:
    die()

modules.sort(key=lambda m: m["module_num"])

# ── merge back into the course source (keep a backup once) ────────────────────
backup = REWORK / "_original-course.json"
if not backup.exists():
    backup.write_text(json.dumps(course, ensure_ascii=False, indent=1))
course["modules"] = modules
SRC.write_text(json.dumps(course, ensure_ascii=False, indent=1))

# ── emit SQL ─────────────────────────────────────────────────────────────────
P = []
P.append("-- 0082_academy_seed_paspor_arab.sql")
P.append("-- Seed: Paspor Perantau Global – Arab Saudi (kursus 'Siap Kerja Arab Saudi', in_app).")
P.append("-- GENERATED by scripts/gen-academy-seed.py from docs/akademi-perantau/paspor-arab-siap-kerja.json.")
P.append("-- Reworked for the learning-experience redesign: chunk-friendly cards, per-card media")
P.append("-- alt, heading anchors, module intro content (outcomes/est_minutes), and per-option quiz")
P.append("-- rationale. Idempotent (ON CONFLICT DO UPDATE) + deterministic uuid5 ids → safe re-apply,")
P.append("-- preserves enrollments. Status stays 'draft' — do NOT publish until payment is live.")
P.append("-- Requires migration 0085 (academy_modules.content).")
P.append("")
P.append("BEGIN;")
P.append("")

# program
pcols = [
    "slug", "title", "subtitle", "category", "delivery_mode", "facilitated_by", "country",
    "is_free", "price", "output_type", "credential_issuer", "credential_delivery",
    "duration_label", "pass_threshold", "content", "status", "sort_order",
]
def pval(c):
    v = program.get(c)
    if c == "content":
        return dq(v or {})
    if c in ("is_free",):
        return "true" if v else "false"
    if c in ("price", "pass_threshold", "sort_order"):
        return "NULL" if v is None else str(v)
    return sql_str(v)

P.append(f"INSERT INTO academy_programs ({', '.join(pcols)}) VALUES")
P.append("  (" + ", ".join(pval(c) for c in pcols) + ")")
P.append("ON CONFLICT (slug) DO UPDATE SET " + ", ".join(
    f"{c} = EXCLUDED.{c}" for c in pcols if c != "slug"
) + ";")
P.append("")

# modules
P.append("INSERT INTO academy_modules (id, program_slug, module_num, title, summary, content, sort_order) VALUES")
mrows = []
for i, m in enumerate(modules):
    mnum = m["module_num"]
    mrows.append(
        "  (" + ", ".join([
            sql_str(mid(slug, mnum)), sql_str(slug), str(mnum),
            sql_str(m["title"]), sql_str(m.get("summary")),
            dq(m.get("content") or {}), str(i),
        ]) + ")"
    )
P.append(",\n".join(mrows))
P.append("ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, summary = EXCLUDED.summary, "
         "content = EXCLUDED.content, module_num = EXCLUDED.module_num, sort_order = EXCLUDED.sort_order;")
P.append("")

# lessons
P.append("INSERT INTO academy_lessons (id, module_id, lesson_num, title, lesson_type, estimated_minutes, pass_threshold, content, sort_order) VALUES")
lrows = []
keyrows = []
for m in modules:
    mnum = m["module_num"]
    for j, l in enumerate(m["lessons"]):
        lnum = l["lesson_num"]
        this_lid = lid(slug, mnum, lnum)
        if l["lesson_type"] == "quiz":
            content = {"questions": l.get("questions", [])}
            pth = l.get("pass_threshold")
            # answer keys → {qid: {correct, weight, explanation, rationale}}
            keys = {}
            for ak in l.get("answerKeys", []):
                qid = ak.get("qid")
                if not qid:
                    continue
                entry = {k: ak[k] for k in ("correct", "weight", "explanation", "rationale", "reread_anchor") if k in ak}
                keys[qid] = entry
            keyrows.append("  (" + ", ".join([sql_str(this_lid), dq(keys)]) + ")")
        else:
            content = {"blocks": l.get("blocks", [])}
            pth = l.get("pass_threshold")
        lrows.append(
            "  (" + ", ".join([
                sql_str(this_lid), sql_str(mid(slug, mnum)), str(lnum),
                sql_str(l["title"]), sql_str(l["lesson_type"]),
                "NULL" if l.get("estimated_minutes") is None else str(l["estimated_minutes"]),
                "NULL" if pth is None else str(pth),
                dq(content), str(j),
            ]) + ")"
        )
P.append(",\n".join(lrows))
P.append("ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, lesson_type = EXCLUDED.lesson_type, "
         "estimated_minutes = EXCLUDED.estimated_minutes, pass_threshold = EXCLUDED.pass_threshold, "
         "content = EXCLUDED.content, lesson_num = EXCLUDED.lesson_num, sort_order = EXCLUDED.sort_order;")
P.append("")

# lesson keys
P.append("INSERT INTO academy_lesson_keys (lesson_id, keys) VALUES")
P.append(",\n".join(keyrows))
P.append("ON CONFLICT (lesson_id) DO UPDATE SET keys = EXCLUDED.keys;")
P.append("")
P.append("COMMIT;")
P.append("")

if errors:
    die()

OUT_SQL.write_text("\n".join(P))

# ── report ───────────────────────────────────────────────────────────────────
total_lessons = sum(len(m["lessons"]) for m in modules)
total_quiz = sum(1 for m in modules for l in m["lessons"] if l["lesson_type"] == "quiz")
total_rationale = sum(
    len(ak.get("rationale", {}))
    for m in modules for l in m["lessons"] if l["lesson_type"] == "quiz"
    for ak in l.get("answerKeys", [])
)
mod_outcomes = sum(len((m.get("content") or {}).get("outcomes", [])) for m in modules)
print(f"OK · {len(modules)} modules · {total_lessons} lessons · {total_quiz} quizzes")
print(f"   module outcomes: {mod_outcomes} · per-option rationales: {total_rationale}")
print(f"   wrote {OUT_SQL.relative_to(ROOT)} ({OUT_SQL.stat().st_size} bytes)")
print(f"   merged source: {SRC.relative_to(ROOT)} (backup: {backup.relative_to(ROOT)})")
if warnings:
    print("\n".join("   ! " + w for w in warnings))
