import Link from "next/link";
import { CorporateFooter } from "@/components/corporate/CorporateFooter";
import { CorporateNav } from "@/components/corporate/CorporateNav";
import { CorporateCtaBanner } from "@/components/corporate/CorporateCtaBanner";

const commitments = [["01", "Trust is designed in", "We make decisions traceable, transparent, and accountable."], ["02", "People are not placements", "We see every hire as the beginning of a long-term working relationship."], ["03", "Readiness matters", "We prepare for a successful transition, not only a successful selection."]];
const differentiators = [["01", "See fit more clearly", "DTG uses job-specific assessment and practical readiness insight to make the hiring conversation more informed."], ["02", "Keep the employer decision central", "Our insight supports, rather than replaces, the employer interview and final selection decision."], ["03", "Stay accountable through the journey", "We connect the workforce brief, selection support, documented process, and aftercare in one partnership."]];
const evidence = [["01", "Verified source", "Each public claim must be traceable to a current, approved source."], ["02", "Clear scope", "Numbers and case stories must state what, where, and when they represent."], ["03", "Permission-led", "Clients, partners, and people are never represented without appropriate approval."]];

export default function AboutPage() { return <main className="corp"><CorporateNav />
  <section className="corp-inner-hero"><p className="corp-kicker">ABOUT DAYA TALENTA GLOBAL</p><h1>Talent movement,<br /><em>made meaningful.</em></h1><p>We are an Indonesian talent partner for international employers who want to grow with care, clarity, and confidence.</p></section>
  <section className="corp-story"><div><p className="corp-kicker">WHO WE ARE</p><h2>A people business<br />with a <em>global view.</em></h2></div><div><p>Daya Talenta Global is part of Dayalima Group, an Indonesian people-strategy group with more than two decades of experience helping organizations and people perform at their best.</p><p>We bring that same rigor to cross-border recruitment: building pathways that are commercially sound for employers and respectful to the people who take them.</p><Link href="/contact">Meet our team →</Link></div></section>
  <section className="corp-values"><p className="corp-kicker">OUR COMMITMENT</p><div>{commitments.map(([number, title, copy]) => <article key={title}><strong>{number}</strong><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
  <section className="corp-service-list" id="why-dtg"><div className="corp-section-heading"><p className="corp-kicker">WHY DTG</p><h2>Make talent fit and readiness <em>visible.</em></h2><p>DTG is the Indonesian workforce partner that makes talent fit and readiness visible, then stays accountable from workforce need through aftercare.</p></div>{differentiators.map(([number, title, copy]) => <article key={title}><span>{number}</span><div><h2>{title}</h2><p>{copy}</p></div><b>↗</b></article>)}</section>
  <section className="corp-story" id="evidence"><div><p className="corp-kicker">EVIDENCE &amp; GOVERNANCE</p><h2>Proof before<br /><em>public promise.</em></h2></div><div><p>DTG will publish credentials, delivery case stories, partner references, and performance information only after the underlying source, time period, scope, and permission have been verified.</p><p>This protects employers, partners, candidates, and the integrity of the information they use to make decisions.</p></div></section>
  <section className="corp-values"><p className="corp-kicker">EVIDENCE PRINCIPLES</p><div>{evidence.map(([number, title, copy]) => <article key={title}><strong>{number}</strong><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
  <CorporateCtaBanner label="START A CONVERSATION" title="Ready to discuss a workforce requirement?" description="Tell us the market, role, estimated volume, and timing you are considering." />
  <CorporateFooter />
</main>; }
